### ISSUE TITLE
Spike: API Management R2

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/Our-Project-Docs#30]
<a rel="Inspiration" href="https://github.com/BCDevExchange/docs/blob/master/discussion/projectstates.md"><img alt="An idea being explored and shaped. Open for discussion, but may never go anywhere." style="border-width:0" src="http://bcdevexchange.org/badge/1.svg" title="An idea being explored and shaped. Open for discussion, but may never go anywhere." /></a> 
# SPIKE:

As a program manager I need to investigate other open source API management technologies so that I can make a strategic decision about the which services and technological framework the exchange should provide for the first year.
# Additional detail:

Background: As part of release 1 the dev team investigated various API magagment tools and settled on using WSO2 as a Proof of Concept to enable the first vision of the BCDevExchange.org site. Output from that is avaialble aa part of this [V1 Architecture Document](https://github.com/BCDevExchange/Our-Project-Docs/blob/master/discussion/architecture.md)

Links:

[Version 1 of live API console as part of R2](https://api.bcdevexchange.org/apim/store/)
# Success criteria:
1. Tech spike microservice architecture (Kong/StrongLoop other?) 
2. Keys via Oauth2 user i.e.: Github
3. UI for console
4. Replication model for api providers 
5. Preserve API providers dns/namespace
6. Policy management (isolated or federated or?)
7. Shared authentication/user id via devexchange account service?
8. decision matrix criteria
9. Inform management team of approach before end of first sprint week
10. attend every management open meeting and demonstrate progress
11. Assumed Todd @kelpisland will lead the spike.
12. Kong/StrongLoop other? - API Keys
13. Kong/StrongLoop other? - Rate control / throttling
14. Gelato? - API Console (Available as of Oct 1)
15. Mashape Analytics - Statistics / Reporting
16. Kong/StrongLoop other? REST API - Ability to integrate with CKAN
# Deliverables:
- Brief summary doc(s) posted to this repo
- Proof of concept (limited in scope to Open511)

**Comment by ll911** [comment]
We should compare StrongLoop with Mashape not just Kong
StrongLoop is an API platform including multiple components that is solely designed for nodeJS
- Arc API lifecycle GUI tool
- LoopBack API node framework
- Data connector (JDBC driver like, but for node to connect multiple data source, like oracle, postgresql, etc)
- API Gateway for node
- Additional component for process management, monitoring, for node

Mashape (including kong, analytic, gelato.io, Postman and mockbin) is current CLOUD API Market Place in Production.
- Kong: API Gateway based on NGINX OPENRESTY
- Mashape market place: Cloud hosted API hubs for consume/provide APIs (on-premises is under development using gelato)
- Mashape analytic plugin: available for both Cloud and on-premises
  Since it doest have API composer, it doesn't limit to any program language.

**Comment by kelpisland** [comment]
Agreed- I don't want to limit the exploration, the more avenues that can be explored in the time we have the better we can map our way forward.

**Comment by kelpisland** [comment]
Added [Spike 30 Meeting Notes 2015-09-22](https://github.com/BCDevExchange/Our-Project-Docs/blob/master/spikes/Spike30-Meeting-Notes-2015-09-22.md)

**Comment by ll911** [comment]
Thx Fred for the detailed feature maps for DevX, I like to add 3M to selection criteria. 
- Microservice Architecture => new SOA, loose couple in functions not loose couple in technology components, REST, ... not just load balanced app tier (X)/ partitioned data tier(Y) scalable but also scalable in function (Z)
- Multi-Language => not restricted to one programming language, so it can be cross platform and cross devices
- Mature in Production => production samples, e.g https://www.publicapis.com/

**Comment by f-w** [comment]
@watkinspd showed me this tool - [swagger.io](http://swagger.io/) which contains a swagger editor with online demo. Is it too geeky to expose raw swagger text to devx api provider?
