### ISSUE TITLE
PRAD 1K UX and prototype

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/Our-Project-Docs#37]
<a rel="Exploration" href="https://github.com/BCDevExchange/docs/blob/master/discussion/projectstates.md"><img alt="Being designed and built, but in the lab. May change, disappear, or be buggy." style="border-width:0" src="http://bcdevexchange.org/badge/2.svg" title="Being designed and built, but in the lab. May change, disappear, or be buggy." /></a>  
# Story:

As a developer I want to be able to access PRAD 1K through the exchange so that i can get work and get paid. 

 As a program owner I want to be able to access PRAD 1K through the exchange so that i can get post work and pay for accepted code. 
# Additional detail:

This is an exploration task to put some UX and business process around PRAD1K.

Continuation of Ticket 168 in Sprint 14.
# Success criteria:
1. Analysis and Reporting
2. Wireframes
# Deliverables:
- Wire Frames
- Process Docs

**Comment by paulroberts68** [comment]
@kelpisland I think the story should read...As a profile page owner I want developers to be able to interact with the PRAD 1K mechanism through the exchange so that I can engage the services of private sector developers to work on my code.

and the success criteria...
1. Develop a journey map for a profile page owner.
2. Develop a journey map for a developer.

**Comment by kelpisland** [comment]
Let's capture both actors (developers & Program owners) so I'll update the story to be more specific.

**Comment by lmullane** [comment]
We have one more user test to complete, scheduled for tomorrow, followed by reporting out.

**Comment by lmullane** [comment]
We have 2 more user test to complete, followed by reporting out.
