### ISSUE TITLE
No license or terms of use listing on DriveBC API profile

### ISSUE THREAD

**Issue by dbhume** [BCDevExchange/Our-Project-Docs#40]

**Comment by lmullane** [comment]
Hi David, there is a link to the OGL in the description on the profile page. Would you like it listed under resources as well?

**Comment by dbhume** [comment]
That sounds good. Seems to me it should be part of the API console documentation tab too.

From: Loren Mullane
Sent: Wednesday, September 23, 2015 12:08 PM
To: BCDevExchange/Our-Project-Docs
Reply To: BCDevExchange/Our-Project-Docs
Cc: Hume, David GCPE:EX
Subject: Re: [Our-Project-Docs] No license or terms of use listing on DriveBC API profile (#40)

Hi David, there is a link to the OGL in the description on the profile page. Would you like it listed under resources as well?

##

**Comment by lmullane** [comment]
@kelpisland Can we add licenses and terms of use (e.g. OGL for Open511) to the documents tab in the console? This should be for all of the APIs with a console. @dbhume

**Comment by lmullane** [comment]
@dbhume I have added the API Terms of Use and OGL under resources on the profile page.

**Comment by kelpisland** [comment]
I think - Yes, but I don't have the access to do that.
@ll911
  can you work with Loren to get the documents added to the Open511 console.

**Comment by ll911** [comment]
both OGL and TC now linked under API console

**Comment by lmullane** [comment]
@dbhume There are fields in the Swagger definition for licensing and terms (when applicable). Once added to the definition this information does appear,  but on the console tab rather than the documents tab; this information is now there for both BC Laws and Open511. Does this work for you? Likely making this information appear on the documents tab would require a change to the Swagger definitions.

**Comment by DavidR8** [comment]
@lmullane can this be closed?
